name: release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: publish releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - name: Build
        run: |
          chmod +x ./release.sh
          ./release.sh
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/er_linux
            release/er_osx
            release/er_windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}